name: UncensorAccentEdition
main: HBIDamian\UncensorAccentEdition\Main
version: 0.2.4
api: 5.0.0
load: POSTWORLD
author: dktapps & HBIDamian
description: Circumvents Microsoft's terrible Minecraft built-in chat filter
website: https://github.com/HBIDamian/Uncensor
